from game import*
pg.display.set_caption("gacha")
screen = pg.display.set_mode((W, H))
sensei=Teacher(0, "adtyu")
stu_init()
sensei.init(len(stu))
sensei.get_stone(100000)
s=StartScene(screen, sensei)
E=NamingScene(screen, sensei)
W=TimeScene(screen, sensei, 200, CALLINGPAGE)
B=TimeScene(screen, sensei, 200, BLACKSUITPAGE)
G=GachaScene(screen, sensei)
s.switch()
s.run()
W.switch()
W.run()
B.switch()
B.run()
G.switch()
G.run()